// Canonical index of the Novaturient Food Groups Reference PDF.
// 6 exchange groups, 40+ example foods per group with serving sizes + exchange counts.
// The AI Coach cites these tables every time it answers a substitution or teaching question,
// so answers always trace back to your teaching document.

import type { ExchangeCategory } from "@/types/app";

export type ReferenceFood = {
  name: string;
  serving: string;
  exchanges: number;
  tips?: string;
};

export type ExchangeGroup = {
  category: ExchangeCategory;
  displayName: string;
  pdfPageHint: string;
  accentClass: string;
  description: string;
  whatOneExchangeProvides: string;
  foods: ReferenceFood[];
};

export const EXCHANGE_GROUP_ORDER: ExchangeCategory[] = [
  "starch",
  "fruit",
  "vegetable",
  "protein",
  "dairy",
  "fat",
];

export const FOOD_GROUPS_REFERENCE: ExchangeGroup[] = [
  {
    category: "starch",
    displayName: "Starches",
    pdfPageHint: "Food Groups Reference · Starches",
    accentClass: "from-[rgba(237,232,245,0.95)]/95 to-[rgba(229,231,237,0.85)]/90",
    description:
      "Choose mostly whole grains and fiber-rich starches. They provide steady energy and help you stay full.",
    whatOneExchangeProvides: "~15 g carbohydrate, ~3 g protein, 0–1 g fat, ~80 kcal",
    foods: [
      { name: "Brown rice", serving: "1/3 cup cooked", exchanges: 1, tips: "Microwave portion cups make meal prep easy." },
      { name: "White rice", serving: "1/3 cup cooked", exchanges: 1 },
      { name: "Wild rice", serving: "1/3 cup cooked", exchanges: 1 },
      { name: "Jasmine rice", serving: "1/3 cup cooked", exchanges: 1 },
      { name: "Basmati rice", serving: "1/3 cup cooked", exchanges: 1 },
      { name: "Oatmeal", serving: "1/2 cup cooked", exchanges: 1, tips: "Oats add soluble fiber for heart health." },
      { name: "Rolled oats (dry)", serving: "3 tbsp", exchanges: 1 },
      { name: "Steel-cut oats (dry)", serving: "2 tbsp", exchanges: 1 },
      { name: "Couscous", serving: "1/3 cup cooked", exchanges: 1 },
      { name: "Bulgur", serving: "1/3 cup cooked", exchanges: 1 },
      { name: "Barley", serving: "1/3 cup cooked", exchanges: 1 },
      { name: "Millet", serving: "1/3 cup cooked", exchanges: 1 },
      { name: "Buckwheat", serving: "1/3 cup cooked", exchanges: 1 },
      { name: "Farro", serving: "1/3 cup cooked", exchanges: 1 },
      { name: "Freekeh", serving: "1/3 cup cooked", exchanges: 1 },
      { name: "Pita bread", serving: "1/2 pita (1 oz)", exchanges: 1 },
      { name: "Whole-wheat bread", serving: "1 slice (1 oz)", exchanges: 1 },
      { name: "White bread", serving: "1 slice (1 oz)", exchanges: 1 },
      { name: "Sourdough bread", serving: "1 slice (1 oz)", exchanges: 1 },
      { name: "Rye bread", serving: "1 slice (1 oz)", exchanges: 1 },
      { name: "Multigrain bread", serving: "1 slice (1 oz)", exchanges: 1 },
      { name: "Bran muffin", serving: "1 small (1 oz)", exchanges: 1 },
      { name: "Bagel (mini)", serving: "1 mini (1 oz)", exchanges: 1 },
      { name: "Bagel (regular)", serving: "1/2 bagel (2 oz)", exchanges: 2 },
      { name: "Croissant (small)", serving: "1/2 small (1 oz)", exchanges: 1.5 },
      { name: "Pancake (small)", serving: "1 small (4 inch)", exchanges: 1 },
      { name: "Waffle (small)", serving: "1 small (4 inch)", exchanges: 1 },
      { name: "French toast", serving: "1 slice", exchanges: 1.5 },
      { name: "Tortilla (medium)", serving: "1 tortilla (8 inch)", exchanges: 2 },
      { name: "Tortilla (small)", serving: "1 tortilla (6 inch)", exchanges: 1 },
      { name: "Corn tortilla", serving: "2 tortillas (6 inch)", exchanges: 1 },
      { name: "Pasta", serving: "1/3 cup cooked", exchanges: 1 },
      { name: "Whole-wheat pasta", serving: "1/3 cup cooked", exchanges: 1 },
      { name: "Brown rice pasta", serving: "1/3 cup cooked", exchanges: 1 },
      { name: "Chickpea pasta", serving: "1/3 cup cooked", exchanges: 1.5 },
      { name: "Ramen noodles", serving: "1/2 block", exchanges: 2 },
      { name: "Quinoa", serving: "1/3 cup cooked", exchanges: 1, tips: "A complete plant protein for vegetarian days." },
      { name: "Amaranth", serving: "1/3 cup cooked", exchanges: 1 },
      { name: "Teff", serving: "1/3 cup cooked", exchanges: 1 },
      { name: "Sorghum", serving: "1/3 cup cooked", exchanges: 1 },
      { name: "Sweet potato", serving: "1 small (3 oz)", exchanges: 1, tips: "Adds vitamins A and C." },
      { name: "Regular potato", serving: "1 small (3 oz) baked", exchanges: 1 },
      { name: "Yam", serving: "1/2 medium (3 oz)", exchanges: 1 },
      { name: "Taro", serving: "1/2 cup cubed cooked", exchanges: 1 },
      { name: "Plantain (ripe)", serving: "1/2 medium fried", exchanges: 2 },
      { name: "Cassava / manioc", serving: "1/3 cup cubed cooked", exchanges: 1 },
      { name: "Parsnips", serving: "1 cup sliced cooked", exchanges: 1 },
      { name: "Green peas", serving: "1/2 cup cooked", exchanges: 1 },
      { name: "Corn", serving: "1/2 cup kernels", exchanges: 1 },
      { name: "Corn on the cob", serving: "1 small ear", exchanges: 1 },
      { name: "Popcorn", serving: "3 cups popped", exchanges: 1, tips: "Air-popped — a big low-fat snack volume." },
      { name: "Rice cakes", serving: "4 cakes", exchanges: 1 },
      { name: "Rice crackers", serving: "8 small", exchanges: 1 },
      { name: "Crackers", serving: "6 saltine-style", exchanges: 1 },
      { name: "Graham crackers", serving: "3 squares", exchanges: 1 },
      { name: "Pretzels (hard)", serving: "12 small twists", exchanges: 1 },
      { name: "English muffin", serving: "1/2 muffin", exchanges: 1 },
      { name: "Crumpet", serving: "1 medium", exchanges: 1 },
      { name: "Scone (plain small)", serving: "1 small (1 oz)", exchanges: 1.5 },
      { name: "Biscotti", serving: "2 small", exchanges: 1 },
      { name: "Matzo / flatbread", serving: "1 sheet", exchanges: 1 },
      { name: "Lentils / beans (starchy)", serving: "1/2 cup cooked", exchanges: 1.5, tips: "Also counts as 1 protein exchange." },
      { name: "Black beans (starchy)", serving: "1/2 cup cooked", exchanges: 1.5 },
      { name: "Kidney beans (starchy)", serving: "1/2 cup cooked", exchanges: 1.5 },
      { name: "Chickpeas (starchy)", serving: "1/2 cup cooked", exchanges: 1.5 },
      { name: "French fries", serving: "1 small order (2 oz)", exchanges: 2.5 },
      { name: "Hash browns", serving: "1/2 cup", exchanges: 1.5 },
      { name: "Mixed grain bowl base", serving: "1/3 cup cooked blend", exchanges: 1 },
    ],
  },
  {
    category: "fruit",
    displayName: "Fruits",
    pdfPageHint: "Food Groups Reference · Fruits",
    accentClass: "from-[rgba(255,245,235,0.95)]/95 to-[rgba(237,232,245,0.75)]/90",
    description:
      "Whole fruits first, juice occasionally. Whole fruits give fiber and better satiety.",
    whatOneExchangeProvides: "~15 g carbohydrate, 0 g fat, ~60 kcal",
    foods: [
      { name: "Apple", serving: "1 small (4 oz)", exchanges: 1, tips: "Crisp varieties stay satisfying longer." },
      { name: "Granny Smith apple", serving: "1 small", exchanges: 1 },
      { name: "Red apple", serving: "1 small", exchanges: 1 },
      { name: "Banana", serving: "1 small (4 oz)", exchanges: 1 },
      { name: "Plantain (green, boiled)", serving: "1/2 cup", exchanges: 1 },
      { name: "Orange", serving: "1 medium", exchanges: 1, tips: "Whole orange beats juice — more fiber." },
      { name: "Mandarin / clementine", serving: "2 medium", exchanges: 1 },
      { name: "Tangerine", serving: "2 medium", exchanges: 1 },
      { name: "Grapefruit", serving: "1/2 medium", exchanges: 1 },
      { name: "Lemon", serving: "2 whole fruit yield", exchanges: 0.5 },
      { name: "Lime", serving: "3 whole fruit yield", exchanges: 0.5 },
      { name: "Pear", serving: "1 small", exchanges: 1 },
      { name: "Bosc pear", serving: "1 small", exchanges: 1 },
      { name: "Mango", serving: "1/2 medium fruit", exchanges: 1 },
      { name: "Pineapple", serving: "3/4 cup chunks", exchanges: 1 },
      { name: "Papaya", serving: "1 cup cubed", exchanges: 1 },
      { name: "Guava", serving: "2 small", exchanges: 1 },
      { name: "Passion fruit", serving: "4 whole", exchanges: 1 },
      { name: "Kiwi", serving: "2 small", exchanges: 1 },
      { name: "Lychee", serving: "10 peeled", exchanges: 1 },
      { name: "Longan", serving: "12 peeled", exchanges: 1 },
      { name: "Peaches", serving: "2 medium", exchanges: 1 },
      { name: "White peach", serving: "1 large", exchanges: 1 },
      { name: "Nectarine", serving: "1 medium", exchanges: 1 },
      { name: "Plum", serving: "2 medium", exchanges: 1 },
      { name: "Apricot", serving: "4 whole", exchanges: 1 },
      { name: "Cherries (sweet)", serving: "12 whole", exchanges: 1 },
      { name: "Sour cherries", serving: "1 cup pitted", exchanges: 1 },
      { name: "Fig (fresh)", serving: "2 whole", exchanges: 1 },
      { name: "Blackberry", serving: "1 cup", exchanges: 1 },
      { name: "Raspberry", serving: "1 cup", exchanges: 1 },
      { name: "Berries (mixed)", serving: "3/4 cup", exchanges: 1 },
      { name: "Strawberries", serving: "1 1/4 cup whole", exchanges: 1, tips: "Large volume for low kcal — great snack." },
      { name: "Blueberries", serving: "3/4 cup", exchanges: 1 },
      { name: "Cranberries (dried sweetened)", serving: "2 tbsp", exchanges: 1 },
      { name: "Cranberry juice cocktail", serving: "1/2 cup", exchanges: 1 },
      { name: "Grapes", serving: "17 small", exchanges: 1 },
      { name: "Green grapes", serving: "17 small", exchanges: 1 },
      { name: "Red grapes", serving: "17 small", exchanges: 1 },
      { name: "Watermelon", serving: "1 1/4 cup diced", exchanges: 1 },
      { name: "Cantaloupe melon", serving: "1 cup cubed", exchanges: 1 },
      { name: "Honeydew melon", serving: "1 1/4 cup cubed", exchanges: 1 },
      { name: "Galia melon", serving: "1 1/4 cup cubed", exchanges: 1 },
      { name: "Pomegranate", serving: "1/2 cup arils", exchanges: 1 },
      { name: "Dragon fruit / pitaya", serving: "3/4 cup cubed", exchanges: 1 },
      { name: "Star fruit / carambola", serving: "1 whole medium", exchanges: 1 },
      { name: "Persimmon", serving: "1 medium", exchanges: 1 },
      { name: "Mulberry", serving: "1 1/4 cup", exchanges: 1 },
      { name: "Coconut (fresh meat)", serving: "2 tbsp", exchanges: 0.5 },
      { name: "Dates (dried)", serving: "3 small (1 tbsp)", exchanges: 1 },
      { name: "Medjool dates", serving: "2 large", exchanges: 1.5 },
      { name: "Raisins", serving: "2 tbsp", exchanges: 1 },
      { name: "Golden raisins", serving: "2 tbsp", exchanges: 1 },
      { name: "Currants (dried)", serving: "3 tbsp", exchanges: 1 },
      { name: "Sultanas", serving: "2 tbsp", exchanges: 1 },
      { name: "Prunes (dried plums)", serving: "3 whole", exchanges: 1, tips: "Gentle fiber for digestive comfort." },
      { name: "Apricots (dried)", serving: "6 halves", exchanges: 1 },
      { name: "Mango (dried)", serving: "4 thin slices", exchanges: 1 },
      { name: "Banana chips", serving: "12 small chips", exchanges: 1 },
      { name: "Candied peel", serving: "2 tbsp", exchanges: 1 },
      { name: "Apple juice", serving: "1/2 cup", exchanges: 1, tips: "1 small glass — easy to overdrink." },
      { name: "Orange juice", serving: "1/2 cup", exchanges: 1 },
      { name: "Grape juice", serving: "1/3 cup", exchanges: 1 },
      { name: "Pineapple juice", serving: "1/2 cup", exchanges: 1 },
      { name: "Grapefruit juice", serving: "1/2 cup", exchanges: 1 },
      { name: "Cranberry juice (unsweetened)", serving: "1/2 cup", exchanges: 0.5 },
      { name: "Prune juice", serving: "1/3 cup", exchanges: 1 },
      { name: "Mango nectar", serving: "1/2 cup", exchanges: 1 },
      { name: "Apricot nectar", serving: "1/2 cup", exchanges: 1 },
      { name: "Guava nectar", serving: "1/2 cup", exchanges: 1 },
      { name: "Fruit smoothie base (no dairy)", serving: "3/4 cup", exchanges: 1 },
      { name: "Frozen mixed berries", serving: "3/4 cup", exchanges: 1 },
      { name: "Frozen mango chunks", serving: "3/4 cup", exchanges: 1 },
      { name: "Frozen pineapple", serving: "3/4 cup", exchanges: 1 },
      { name: "Applesauce (unsweetened)", serving: "1/2 cup", exchanges: 1 },
      { name: "Pear sauce", serving: "1/2 cup", exchanges: 1 },
      { name: "Fruit compote (sugar-free)", serving: "1/2 cup", exchanges: 1 },
    ],
  },
  {
    category: "vegetable",
    displayName: "Vegetables",
    pdfPageHint: "Food Groups Reference · Vegetables",
    accentClass: "from-[rgba(232,245,232,0.95)]/95 to-[rgba(229,231,237,0.75)]/90",
    description:
      "Fill half your plate with non-starchy vegetables. Think volume + color — few exchanges, lots of nutrition.",
    whatOneExchangeProvides: "~5 g carbohydrate, 2 g protein, 0 g fat, ~25 kcal (0.5 exchange per serving)",
    foods: [
      { name: "Cucumber", serving: "1 cup sliced raw", exchanges: 0.5 },
      { name: "Persian cucumber", serving: "1 1/2 whole", exchanges: 0.5 },
      { name: "Mixed salad greens", serving: "2 cups raw", exchanges: 0.5, tips: "Big volume — fills up the plate." },
      { name: "Iceberg lettuce", serving: "2 1/2 cups shredded", exchanges: 0.5 },
      { name: "Romaine lettuce", serving: "2 cups shredded", exchanges: 0.5 },
      { name: "Butter lettuce / bibb", serving: "2 cups whole leaves", exchanges: 0.5 },
      { name: "Green leaf lettuce", serving: "2 cups shredded", exchanges: 0.5 },
      { name: "Red leaf lettuce", serving: "2 cups shredded", exchanges: 0.5 },
      { name: "Arugula / rocket", serving: "2 cups whole", exchanges: 0.5 },
      { name: "Kale", serving: "1 1/2 cups chopped raw", exchanges: 0.5 },
      { name: "Baby spinach", serving: "2 cups raw", exchanges: 0.5 },
      { name: "Spinach", serving: "2 cups raw / 1/2 cup cooked", exchanges: 0.5, tips: "Cooking shrinks volume but preserves iron." },
      { name: "Collard greens", serving: "1 cup chopped raw", exchanges: 0.5 },
      { name: "Mustard greens", serving: "1 cup chopped raw", exchanges: 0.5 },
      { name: "Turnip greens", serving: "1 cup chopped raw", exchanges: 0.5 },
      { name: "Swiss chard", serving: "1 1/4 cups chopped raw", exchanges: 0.5 },
      { name: "Beet greens", serving: "1 cup chopped raw", exchanges: 0.5 },
      { name: "Dandelion greens", serving: "1 1/4 cups raw", exchanges: 0.5 },
      { name: "Watercress", serving: "2 cups whole sprigs", exchanges: 0.5 },
      { name: "Endive", serving: "1 1/2 medium heads", exchanges: 0.5 },
      { name: "Radicchio", serving: "1 1/2 cups shredded", exchanges: 0.5 },
      { name: "Frisée / curly endive", serving: "2 cups shredded", exchanges: 0.5 },
      { name: "Escarole", serving: "2 cups shredded", exchanges: 0.5 },
      { name: "Mizuna", serving: "2 cups chopped", exchanges: 0.5 },
      { name: "Tat soi", serving: "1 1/2 cups whole", exchanges: 0.5 },
      { name: "Carrots", serving: "1 cup raw sticks / 1/2 cup cooked", exchanges: 0.5 },
      { name: "Baby carrots", serving: "12 pieces", exchanges: 0.5 },
      { name: "Parsnips", serving: "1 cup raw sticks", exchanges: 1 },
      { name: "Beetroot", serving: "1 cup raw sliced", exchanges: 0.5 },
      { name: "Turnip", serving: "1 cup cubed raw", exchanges: 0.5 },
      { name: "Radish", serving: "12 whole", exchanges: 0.5 },
      { name: "Daikon radish", serving: "1 1/2 cups sliced", exchanges: 0.5 },
      { name: "Tomato", serving: "1 medium whole / 1 cup sliced", exchanges: 0.5 },
      { name: "Cherry tomatoes", serving: "1 cup whole", exchanges: 0.5 },
      { name: "Roma tomato", serving: "2 whole", exchanges: 0.5 },
      { name: "Heirloom tomato", serving: "1/2 large sliced", exchanges: 0.5 },
      { name: "Tomatillo", serving: "1 cup whole", exchanges: 0.5 },
      { name: "Bell peppers", serving: "1 cup sliced", exchanges: 0.5, tips: "Red peppers = more vitamin C than oranges by weight." },
      { name: "Green pepper", serving: "1 cup sliced", exchanges: 0.5 },
      { name: "Red pepper", serving: "1 cup sliced", exchanges: 0.5 },
      { name: "Yellow pepper", serving: "1 cup sliced", exchanges: 0.5 },
      { name: "Orange pepper", serving: "1 cup sliced", exchanges: 0.5 },
      { name: "Chili pepper (mild)", serving: "2 whole", exchanges: 0.5 },
      { name: "Jalapeño", serving: "4 whole", exchanges: 0.5 },
      { name: "Poblano", serving: "2 whole", exchanges: 0.5 },
      { name: "Anaheim pepper", serving: "2 whole", exchanges: 0.5 },
      { name: "Broccoli", serving: "1 cup florets", exchanges: 0.5, tips: "Steamed 2 minutes — keeps texture & nutrition." },
      { name: "Broccoli rabe / rapini", serving: "1 cup chopped raw", exchanges: 0.5 },
      { name: "Cauliflower", serving: "1 cup florets", exchanges: 0.5 },
      { name: "Purple cauliflower", serving: "1 cup florets", exchanges: 0.5 },
      { name: "Romanesco", serving: "1 cup florets", exchanges: 0.5 },
      { name: "Cabbage", serving: "1 cup shredded", exchanges: 0.5 },
      { name: "Red cabbage", serving: "1 cup shredded", exchanges: 0.5 },
      { name: "Savoy cabbage", serving: "1 cup shredded", exchanges: 0.5 },
      { name: "Napa cabbage", serving: "1 1/4 cups shredded", exchanges: 0.5 },
      { name: "Bok choy", serving: "1 1/2 cups chopped", exchanges: 0.5 },
      { name: "Baby bok choy", serving: "4 whole heads", exchanges: 0.5 },
      { name: "Choy sum", serving: "1 1/2 cups chopped", exchanges: 0.5 },
      { name: "Gai lan / Chinese broccoli", serving: "1 1/4 cups chopped", exchanges: 0.5 },
      { name: "Brussels sprouts", serving: "8 whole medium", exchanges: 0.5 },
      { name: "Celery", serving: "3 stalks", exchanges: 0.5 },
      { name: "Fennel bulb", serving: "1 cup sliced raw", exchanges: 0.5 },
      { name: "Green beans", serving: "1/2 cup cooked", exchanges: 0.5 },
      { name: "French beans / haricot vert", serving: "3/4 cup raw", exchanges: 0.5 },
      { name: "Wax beans", serving: "1/2 cup cooked", exchanges: 0.5 },
      { name: "Sugar snap peas", serving: "1 cup whole", exchanges: 0.5 },
      { name: "Snow peas", serving: "1 cup whole", exchanges: 0.5 },
      { name: "Asparagus", serving: "6 spears", exchanges: 0.5 },
      { name: "White asparagus", serving: "6 spears", exchanges: 0.5 },
      { name: "Zucchini", serving: "1 cup sliced", exchanges: 0.5 },
      { name: "Yellow squash", serving: "1 cup sliced", exchanges: 0.5 },
      { name: "Crookneck squash", serving: "1 cup sliced", exchanges: 0.5 },
      { name: "Pattypan squash", serving: "1 medium", exchanges: 0.5 },
      { name: "Acorn squash", serving: "1/2 cup baked", exchanges: 1 },
      { name: "Butternut squash", serving: "1/2 cup baked", exchanges: 1 },
      { name: "Spaghetti squash", serving: "3/4 cup cooked strands", exchanges: 0.5 },
      { name: "Kabocha squash", serving: "1/2 cup baked", exchanges: 1 },
      { name: "Hubbard squash", serving: "1/2 cup baked", exchanges: 1 },
      { name: "Pumpkin", serving: "1/2 cup baked", exchanges: 1 },
      { name: "Okra", serving: "8 whole pods", exchanges: 0.5 },
      { name: "Eggplant", serving: "1 cup cubed cooked", exchanges: 0.5 },
      { name: "Baby eggplant", serving: "4 whole", exchanges: 0.5 },
      { name: "Onion", serving: "1 cup sliced raw", exchanges: 0.5 },
      { name: "Red onion", serving: "1 cup sliced raw", exchanges: 0.5 },
      { name: "Yellow onion", serving: "1 cup sliced raw", exchanges: 0.5 },
      { name: "White onion", serving: "1 cup sliced raw", exchanges: 0.5 },
      { name: "Sweet onion", serving: "1 cup sliced raw", exchanges: 0.5 },
      { name: "Shallots", serving: "6 whole peeled", exchanges: 0.5 },
      { name: "Leek", serving: "1 cup sliced raw", exchanges: 0.5 },
      { name: "Scallions / green onion", serving: "1 cup chopped", exchanges: 0.5 },
      { name: "Garlic", serving: "8 cloves", exchanges: 0.5 },
      { name: "Mushrooms", serving: "1 cup sliced", exchanges: 0.5 },
      { name: "Cremini mushrooms", serving: "1 cup sliced", exchanges: 0.5 },
      { name: "Shiitake mushrooms", serving: "4 whole medium", exchanges: 0.5 },
      { name: "Oyster mushrooms", serving: "1 cup whole", exchanges: 0.5 },
      { name: "Portobello mushroom", serving: "1 medium cap", exchanges: 0.5 },
      { name: "Enoki mushrooms", serving: "1 package (40g)", exchanges: 0.5 },
      { name: "Artichoke", serving: "1 medium steamed", exchanges: 1 },
      { name: "Artichoke hearts", serving: "4 whole canned", exchanges: 0.5 },
      { name: "Hearts of palm", serving: "6 whole slices", exchanges: 0.5 },
      { name: "Celery root / celeriac", serving: "1 cup cubed raw", exchanges: 0.5 },
      { name: "Jicama", serving: "1 cup cubed raw", exchanges: 0.5 },
      { name: "Rutabaga", serving: "1 cup cubed raw", exchanges: 0.5 },
      { name: "Kohlrabi", serving: "1 cup cubed raw", exchanges: 0.5 },
      { name: "Chayote", serving: "1 cup cubed raw", exchanges: 0.5 },
      { name: "Bamboo shoots", serving: "1 cup sliced", exchanges: 0.5 },
      { name: "Water chestnuts", serving: "1/2 cup sliced", exchanges: 0.5 },
      { name: "Corn salad / mâche", serving: "2 cups whole", exchanges: 0.5 },
      { name: "Microgreens (any)", serving: "2 cups", exchanges: 0.5 },
      { name: "Avocado (very small portion)", serving: "2 thin slices", exchanges: 0.5 },
      { name: "Pickled cucumber", serving: "1 cup slices", exchanges: 0.5 },
      { name: "Sauerkraut (unsalted)", serving: "1/2 cup", exchanges: 0.5 },
      { name: "Kimchi (unsweetened)", serving: "1/2 cup", exchanges: 0.5 },
    ],
  },
  {
    category: "protein",
    displayName: "Protein",
    pdfPageHint: "Food Groups Reference · Protein",
    accentClass: "from-[rgba(255,232,232,0.95)]/95 to-[rgba(237,232,245,0.85)]/90",
    description:
      "Protein is the anchor of every meal. Rotate sources so you get variety and never feel stuck on one food.",
    whatOneExchangeProvides: "~7 g protein, ~1 g fat (lean), ~55–75 kcal depending on fat grade",
    foods: [
      { name: "Chicken breast", serving: "1 oz cooked", exchanges: 1, tips: "Batch-poach or grill — most versatile protein." },
      { name: "Chicken breast (skinless)", serving: "1 oz cooked", exchanges: 1 },
      { name: "Chicken thigh (lean)", serving: "1 oz cooked", exchanges: 1 },
      { name: "Chicken thigh (skinless)", serving: "1 oz cooked", exchanges: 1.2 },
      { name: "Chicken drumstick (lean)", serving: "1 oz cooked meat", exchanges: 1 },
      { name: "Chicken wing (lean meat only)", serving: "2 wings", exchanges: 1 },
      { name: "Chicken liver", serving: "1 oz cooked", exchanges: 1 },
      { name: "Turkey breast", serving: "1 oz cooked / 1 slice deli", exchanges: 1 },
      { name: "Turkey thigh (lean)", serving: "1 oz cooked", exchanges: 1 },
      { name: "Ground turkey (lean 93/7)", serving: "1 oz cooked", exchanges: 1 },
      { name: "Turkey bacon (light)", serving: "2 strips", exchanges: 1 },
      { name: "Turkey deli slices", serving: "1 oz / 3 slices", exchanges: 1 },
      { name: "Chicken deli slices", serving: "1 oz / 3 slices", exchanges: 1 },
      { name: "Lean beef", serving: "1 oz cooked", exchanges: 1, tips: "Round or sirloin cuts are lowest fat." },
      { name: "Beef sirloin", serving: "1 oz cooked", exchanges: 1 },
      { name: "Beef tenderloin", serving: "1 oz cooked", exchanges: 1 },
      { name: "Beef eye of round", serving: "1 oz cooked", exchanges: 1 },
      { name: "Beef top round", serving: "1 oz cooked", exchanges: 1 },
      { name: "Beef bottom round", serving: "1 oz cooked", exchanges: 1 },
      { name: "Beef flank steak", serving: "1 oz cooked", exchanges: 1 },
      { name: "Lean ground beef (90/10)", serving: "1 oz cooked", exchanges: 1 },
      { name: "Extra lean ground beef (95/5)", serving: "1 oz cooked", exchanges: 1 },
      { name: "Veal (lean cutlet)", serving: "1 oz cooked", exchanges: 1 },
      { name: "Veal liver", serving: "1 oz cooked", exchanges: 1 },
      { name: "Lamb (lean)", serving: "1 oz cooked", exchanges: 1 },
      { name: "Lamb leg (lean)", serving: "1 oz cooked", exchanges: 1 },
      { name: "Lamb loin chop (lean)", serving: "1 oz cooked", exchanges: 1 },
      { name: "Pork tenderloin", serving: "1 oz cooked", exchanges: 1 },
      { name: "Pork loin (lean)", serving: "1 oz cooked", exchanges: 1 },
      { name: "Pork chop (center-cut, lean)", serving: "1 oz cooked", exchanges: 1 },
      { name: "Pork ham (lean, cooked)", serving: "1 oz", exchanges: 1 },
      { name: "Canadian bacon", serving: "1 1/2 oz", exchanges: 1.5 },
      { name: "Bacon (pork, light)", serving: "2 strips cooked", exchanges: 1.5 },
      { name: "Duck breast (skinless)", serving: "1 oz cooked", exchanges: 1.5 },
      { name: "Quail", serving: "1 whole (cooked meat)", exchanges: 1 },
      { name: "Rabbit (lean)", serving: "1 oz cooked", exchanges: 1 },
      { name: "Game meat (venison)", serving: "1 oz cooked", exchanges: 1 },
      { name: "Bison (lean)", serving: "1 oz cooked", exchanges: 1 },
      { name: "Ostrich (lean)", serving: "1 oz cooked", exchanges: 1 },
      { name: "Salmon", serving: "1 oz cooked", exchanges: 1, tips: "Adds omega-3 — 2–3 x per week is ideal." },
      { name: "Atlantic salmon", serving: "1 oz cooked", exchanges: 1 },
      { name: "Coho / sockeye salmon", serving: "1 oz cooked", exchanges: 1 },
      { name: "Smoked salmon (lox)", serving: "1 oz", exchanges: 1 },
      { name: "Tuna (canned in water)", serving: "1 oz drained", exchanges: 1 },
      { name: "Tuna steak", serving: "1 oz cooked", exchanges: 1 },
      { name: "Sardines (canned)", serving: "3 whole", exchanges: 1.5 },
      { name: "Anchovies", serving: "6 whole fillets", exchanges: 0.5 },
      { name: "Mackerel", serving: "1 oz cooked", exchanges: 1.5 },
      { name: "Herring", serving: "1 oz cooked", exchanges: 1.5 },
      { name: "Trout", serving: "1 oz cooked", exchanges: 1 },
      { name: "Rainbow trout", serving: "1 oz cooked", exchanges: 1 },
      { name: "White fish (cod, haddock)", serving: "1 oz cooked", exchanges: 1 },
      { name: "Cod fillet", serving: "1 oz cooked", exchanges: 1 },
      { name: "Haddock", serving: "1 oz cooked", exchanges: 1 },
      { name: "Hake", serving: "1 oz cooked", exchanges: 1 },
      { name: "Pollock", serving: "1 oz cooked", exchanges: 1 },
      { name: "Halibut", serving: "1 oz cooked", exchanges: 1 },
      { name: "Flounder / sole", serving: "1 oz cooked", exchanges: 1 },
      { name: "Tilapia", serving: "1 oz cooked", exchanges: 1 },
      { name: "Catfish", serving: "1 oz cooked", exchanges: 1 },
      { name: "Grouper", serving: "1 oz cooked", exchanges: 1 },
      { name: "Snapper", serving: "1 oz cooked", exchanges: 1 },
      { name: "Sea bass", serving: "1 oz cooked", exchanges: 1 },
      { name: "Mahi mahi", serving: "1 oz cooked", exchanges: 1 },
      { name: "Swordfish", serving: "1 oz cooked", exchanges: 1 },
      { name: "Shrimp", serving: "5 large", exchanges: 1, tips: "Fast to cook — stir-fry or steam 2 min." },
      { name: "Prawns", serving: "4 large", exchanges: 1 },
      { name: "Scallops", serving: "3 medium", exchanges: 1 },
      { name: "Crab / surimi", serving: "1 oz", exchanges: 1 },
      { name: "King crab legs", serving: "1 oz meat", exchanges: 1 },
      { name: "Snow crab legs", serving: "1 1/2 oz meat", exchanges: 1.5 },
      { name: "Lobster", serving: "1 oz tail meat", exchanges: 1 },
      { name: "Clams", serving: "6 small whole / 2 oz meat", exchanges: 1 },
      { name: "Mussels", serving: "10 in shell / 2 oz meat", exchanges: 1 },
      { name: "Oysters", serving: "6 medium", exchanges: 1.5 },
      { name: "Calamari / squid", serving: "1 1/4 oz", exchanges: 1 },
      { name: "Octopus", serving: "1 oz cooked", exchanges: 1 },
      { name: "Caviar (small portion)", serving: "2 tbsp", exchanges: 1 },
      { name: "Eggs", serving: "1 large egg", exchanges: 1, tips: "Whole eggs are fine for most people." },
      { name: "Egg whites", serving: "2 egg whites", exchanges: 1 },
      { name: "Egg yolks only", serving: "2 large yolks", exchanges: 1 },
      { name: "Egg substitute", serving: "1/4 cup", exchanges: 1 },
      { name: "Quail eggs", serving: "5 whole", exchanges: 1 },
      { name: "Greek yogurt (nonfat)", serving: "1/3 cup", exchanges: 1, tips: "Counts as dairy too — swap either place!" },
      { name: "Greek yogurt (low-fat)", serving: "1/3 cup", exchanges: 1 },
      { name: "Icelandic skyr", serving: "1/3 cup", exchanges: 1 },
      { name: "Cottage cheese (low-fat)", serving: "1/4 cup", exchanges: 1 },
      { name: "Ricotta (part-skim)", serving: "1/3 cup", exchanges: 1 },
      { name: "Lentils (cooked)", serving: "1/2 cup", exchanges: 2, tips: "Plant-based — keep portions generous." },
      { name: "Red lentils (cooked)", serving: "1/2 cup", exchanges: 2 },
      { name: "Split peas (cooked)", serving: "1/2 cup", exchanges: 2 },
      { name: "Black beans (protein)", serving: "1/2 cup", exchanges: 1.5 },
      { name: "Kidney beans (protein)", serving: "1/2 cup", exchanges: 1.5 },
      { name: "Pinto beans", serving: "1/2 cup", exchanges: 1.5 },
      { name: "Cannellini beans", serving: "1/2 cup", exchanges: 1.5 },
      { name: "Navy beans", serving: "1/2 cup", exchanges: 1.5 },
      { name: "Great northern beans", serving: "1/2 cup", exchanges: 1.5 },
      { name: "Lima beans", serving: "1/2 cup", exchanges: 1.5 },
      { name: "Fava beans", serving: "1/2 cup shelled", exchanges: 1.5 },
      { name: "Mung beans", serving: "1/2 cup cooked", exchanges: 1.5 },
      { name: "Adzuki beans", serving: "1/2 cup cooked", exchanges: 1.5 },
      { name: "Chickpeas / hummus base", serving: "1/2 cup cooked", exchanges: 1.5 },
      { name: "Edamame (green soybeans)", serving: "1/3 cup shelled", exchanges: 1 },
      { name: "Tofu (firm)", serving: "3 oz / 1/2 cup cubed", exchanges: 1, tips: "Press first, then pan-crisp for texture." },
      { name: "Tofu (extra firm)", serving: "3 oz", exchanges: 1 },
      { name: "Tofu (silken soft)", serving: "1/2 cup", exchanges: 1 },
      { name: "Tempeh", serving: "1 oz", exchanges: 1 },
      { name: "Seitan / wheat meat", serving: "1 oz", exchanges: 1.5 },
      { name: "Textured vegetable protein (TVP)", serving: "1/4 cup dry rehydrated", exchanges: 1 },
      { name: "Soy milk (high protein)", serving: "1 cup", exchanges: 1.5 },
      { name: "Pea protein isolate shake", serving: "1 scoop (20g)", exchanges: 3 },
      { name: "Whey protein isolate shake", serving: "1 scoop (20g)", exchanges: 3 },
      { name: "Lean ham / deli", serving: "1 oz sliced", exchanges: 1 },
      { name: "Roast beef deli slices", serving: "1 oz / 2 slices", exchanges: 1 },
      { name: "Pastrami (lean)", serving: "1 oz", exchanges: 1 },
      { name: "Corned beef (lean)", serving: "1 oz", exchanges: 1 },
      { name: "Prosciutto", serving: "1 oz (3 thin slices)", exchanges: 1.5 },
      { name: "Chorizo (low-fat)", serving: "1 oz cooked", exchanges: 2 },
      { name: "Jerky (beef, low-sugar)", serving: "1 oz", exchanges: 1.5 },
      { name: "Protein bar (low-sugar)", serving: "1 bar", exchanges: 3 },
    ],
  },
  {
    category: "dairy",
    displayName: "Dairy",
    pdfPageHint: "Food Groups Reference · Dairy",
    accentClass: "from-[rgba(255,255,255,0.98)]/98 to-[rgba(229,231,237,0.75)]/90",
    description:
      "Choose low-fat or skim most days. Greek yogurt and kefir help with satiety and gut variety.",
    whatOneExchangeProvides: "~12 g carb, 8 g protein, 0–8 g fat, ~100–120 kcal",
    foods: [
      { name: "Milk (skim / low-fat)", serving: "1 cup", exchanges: 1 },
      { name: "Milk (whole)", serving: "1 cup", exchanges: 1.5 },
      { name: "Milk (2% reduced-fat)", serving: "1 cup", exchanges: 1 },
      { name: "Milk (1% low-fat)", serving: "1 cup", exchanges: 1 },
      { name: "Laban / Ayran (low-salt)", serving: "1 cup", exchanges: 1 },
      { name: "Kefir", serving: "1 cup", exchanges: 1, tips: "Fermented option — great for digestive comfort." },
      { name: "Buttermilk (low-fat)", serving: "1 cup", exchanges: 1 },
      { name: "Evaporated milk", serving: "1/2 cup", exchanges: 1.5 },
      { name: "Condensed milk (sweetened)", serving: "2 tbsp", exchanges: 1.5 },
      { name: "Powdered milk", serving: "3 tbsp rehydrated", exchanges: 1 },
      { name: "Goat milk", serving: "1 cup", exchanges: 1.2 },
      { name: "Sheep milk", serving: "3/4 cup", exchanges: 1.2 },
      { name: "Buffalo milk", serving: "1/2 cup", exchanges: 1.5 },
      { name: "Camel milk", serving: "3/4 cup", exchanges: 1 },
      { name: "Lactose-free milk", serving: "1 cup", exchanges: 1 },
      { name: "Chocolate milk (low-fat)", serving: "3/4 cup", exchanges: 1 },
      { name: "Strawberry milk (low-fat)", serving: "3/4 cup", exchanges: 1 },
      { name: "Vanilla flavored milk (low-fat)", serving: "3/4 cup", exchanges: 1 },
      { name: "Soy milk (unsweetened)", serving: "1 cup", exchanges: 1 },
      { name: "Almond milk (unsweetened)", serving: "2 cups", exchanges: 0.5 },
      { name: "Oat milk (unsweetened)", serving: "1 cup", exchanges: 1 },
      { name: "Rice milk (unsweetened)", serving: "1 cup", exchanges: 1.5 },
      { name: "Cashew milk (unsweetened)", serving: "1 1/2 cup", exchanges: 0.5 },
      { name: "Hemp milk (unsweetened)", serving: "1 cup", exchanges: 1 },
      { name: "Yogurt (plain low-fat)", serving: "3/4 cup", exchanges: 1 },
      { name: "Yogurt (plain nonfat)", serving: "3/4 cup", exchanges: 1 },
      { name: "Yogurt (plain whole milk)", serving: "1/2 cup", exchanges: 1 },
      { name: "Greek yogurt (plain nonfat)", serving: "2/3 cup", exchanges: 1, tips: "Higher protein than regular yogurt." },
      { name: "Greek yogurt (plain low-fat)", serving: "2/3 cup", exchanges: 1 },
      { name: "Greek yogurt (vanilla low-fat)", serving: "1/2 cup", exchanges: 1 },
      { name: "Labneh (strained yogurt)", serving: "1/3 cup", exchanges: 1 },
      { name: "Icelandic skyr (plain)", serving: "2/3 cup", exchanges: 1 },
      { name: "Cottage cheese (low-fat)", serving: "1 cup", exchanges: 2, tips: "Also counts as protein — great on salads." },
      { name: "Cottage cheese (nonfat)", serving: "1 cup", exchanges: 2 },
      { name: "Ricotta (part-skim)", serving: "1/3 cup", exchanges: 1 },
      { name: "Ricotta (whole milk)", serving: "1/4 cup", exchanges: 1 },
      { name: "Mascarpone (light)", serving: "2 tbsp", exchanges: 1 },
      { name: "Cream cheese (light)", serving: "2 tbsp", exchanges: 1 },
      { name: "Cream cheese (regular)", serving: "1 tbsp", exchanges: 1 },
      { name: "Cheese cubes (low-fat)", serving: "1 oz (3 small cubes)", exchanges: 1 },
      { name: "American cheese (light)", serving: "1 1/2 oz", exchanges: 1 },
      { name: "Feta (light)", serving: "1 oz", exchanges: 1 },
      { name: "Feta (regular)", serving: "3/4 oz", exchanges: 1 },
      { name: "Halloumi", serving: "1 oz", exchanges: 1, tips: "Salty — rinse before pan-grilling." },
      { name: "Mozzarella (low-moisture)", serving: "1 oz", exchanges: 1 },
      { name: "Fresh mozzarella (buffalo)", serving: "1 oz", exchanges: 1 },
      { name: "String cheese (low-fat)", serving: "1 stick (1 oz)", exchanges: 1 },
      { name: "Ricotta salata", serving: "1 oz", exchanges: 1 },
      { name: "Goat cheese (soft)", serving: "1 oz", exchanges: 1.5 },
      { name: "Feta crumbles (light)", serving: "1 oz", exchanges: 1 },
      { name: "Sheep cheese", serving: "3/4 oz", exchanges: 1 },
      { name: "Cheddar (light / reduced-fat)", serving: "1 oz", exchanges: 1 },
      { name: "Cheddar (sharp, regular)", serving: "3/4 oz", exchanges: 1 },
      { name: "Mild cheddar", serving: "3/4 oz", exchanges: 1 },
      { name: "Gouda (light)", serving: "1 oz", exchanges: 1 },
      { name: "Gouda (regular)", serving: "3/4 oz", exchanges: 1 },
      { name: "Swiss (light)", serving: "1 oz", exchanges: 1 },
      { name: "Swiss (regular)", serving: "3/4 oz", exchanges: 1 },
      { name: "Emmental", serving: "3/4 oz", exchanges: 1 },
      { name: "Gruyère", serving: "3/4 oz", exchanges: 1 },
      { name: "Parmesan (grated)", serving: "2 tbsp / 0.75 oz", exchanges: 1 },
      { name: "Pecorino romano", serving: "2 tbsp", exchanges: 1 },
      { name: "Romano cheese", serving: "2 tbsp", exchanges: 1 },
      { name: "Asiago", serving: "1 oz", exchanges: 1 },
      { name: "Provolone (light)", serving: "1 oz", exchanges: 1 },
      { name: "Monterey jack", serving: "3/4 oz", exchanges: 1 },
      { name: "Colby jack", serving: "3/4 oz", exchanges: 1 },
      { name: "Havarti (light)", serving: "1 oz", exchanges: 1 },
      { name: "Brie (light)", serving: "1 oz", exchanges: 1.5 },
      { name: "Camembert (light)", serving: "1 oz", exchanges: 1.5 },
      { name: "Blue cheese crumbles", serving: "1 oz", exchanges: 1.5 },
      { name: "Gorgonzola (light)", serving: "1 oz", exchanges: 1.5 },
      { name: "Roquefort", serving: "3/4 oz", exchanges: 1.5 },
      { name: "Manchego", serving: "1 oz", exchanges: 1.5 },
      { name: "Paneer", serving: "1 oz", exchanges: 1 },
      { name: "Queso fresco", serving: "1 oz", exchanges: 1 },
      { name: "Cottage cheese (low-fat)", serving: "1 cup", exchanges: 2 },
      { name: "Cheese spread (light)", serving: "3 tbsp", exchanges: 1 },
      { name: "Cheese whiz (light)", serving: "2 tbsp", exchanges: 1 },
      { name: "Ice milk / light ice cream", serving: "1/2 cup", exchanges: 1.5 },
      { name: "Frozen yogurt (light)", serving: "1/2 cup", exchanges: 1.5 },
      { name: "Gelato (light)", serving: "1/3 cup", exchanges: 1.5 },
      { name: "Sherbet", serving: "1/3 cup", exchanges: 1.5 },
      { name: "Sorbet", serving: "1/2 cup", exchanges: 2 },
      { name: "Pudding (sugar-free, low-fat)", serving: "1/2 cup", exchanges: 1 },
      { name: "Custard (light)", serving: "1/2 cup", exchanges: 1.5 },
      { name: "Flan (sugar-free, low-fat)", serving: "1/2 cup", exchanges: 1.5 },
      { name: "Tapioca pudding (sugar-free)", serving: "1/2 cup", exchanges: 1 },
      { name: "Rice pudding (sugar-free, low-fat)", serving: "1/2 cup", exchanges: 1.5 },
      { name: "Semolina pudding (light)", serving: "1/3 cup", exchanges: 1 },
      { name: "Milkshake (small, light)", serving: "1/2 cup", exchanges: 3 },
      { name: "Hot cocoa (made with skim milk, no sugar)", serving: "1 cup", exchanges: 1 },
      { name: "Chai latte (made with skim milk, no sugar)", serving: "1 cup", exchanges: 1 },
      { name: "Latte (skim milk, no sugar)", serving: "1 cup", exchanges: 1 },
      { name: "Cappuccino (skim milk, no sugar)", serving: "1 cup", exchanges: 0.5 },
      { name: "Macchiato (milk only)", serving: "1 cup", exchanges: 0.5 },
      { name: "Smoothie (dairy base, no added sugar)", serving: "1 cup", exchanges: 1.5 },
    ],
  },
  {
    category: "fat",
    displayName: "Fats",
    pdfPageHint: "Food Groups Reference · Fats",
    accentClass: "from-[rgba(255,247,232,0.95)]/95 to-[rgba(237,232,245,0.85)]/90",
    description:
      "Keep fat portions small but don't omit them. Fats add flavor and keep hunger away.",
    whatOneExchangeProvides: "~5 g fat, ~45 kcal per 1 fat exchange",
    foods: [
      { name: "Olive oil", serving: "1 tsp", exchanges: 1, tips: "Drizzle on vegetables, don't deep-fry." },
      { name: "Extra virgin olive oil", serving: "1 tsp", exchanges: 1 },
      { name: "Canola oil", serving: "1 tsp", exchanges: 1 },
      { name: "Sunflower oil", serving: "1 tsp", exchanges: 1 },
      { name: "Safflower oil", serving: "1 tsp", exchanges: 1 },
      { name: "Soybean oil", serving: "1 tsp", exchanges: 1 },
      { name: "Corn oil", serving: "1 tsp", exchanges: 1 },
      { name: "Vegetable oil blend", serving: "1 tsp", exchanges: 1 },
      { name: "Peanut oil", serving: "1 tsp", exchanges: 1 },
      { name: "Sesame oil", serving: "1 tsp", exchanges: 1 },
      { name: "Toasted sesame oil", serving: "1 tsp", exchanges: 1 },
      { name: "Walnut oil", serving: "1 tsp", exchanges: 1 },
      { name: "Almond oil", serving: "1 tsp", exchanges: 1 },
      { name: "Avocado oil", serving: "1 tsp", exchanges: 1 },
      { name: "Grape seed oil", serving: "1 tsp", exchanges: 1 },
      { name: "Flaxseed oil", serving: "1 tsp", exchanges: 1 },
      { name: "Pumpkin seed oil", serving: "1 tsp", exchanges: 1 },
      { name: "Coconut oil (virgin)", serving: "1 tsp", exchanges: 1.5 },
      { name: "Palm oil", serving: "1 tsp", exchanges: 1.5 },
      { name: "Ghee / clarified butter", serving: "1 tsp", exchanges: 1.5 },
      { name: "Butter / margarine", serving: "1 tsp", exchanges: 1 },
      { name: "Butter (salted)", serving: "1 tsp", exchanges: 1 },
      { name: "Butter (unsalted)", serving: "1 tsp", exchanges: 1 },
      { name: "Margarine (soft tub, light)", serving: "1 1/2 tsp", exchanges: 1 },
      { name: "Margarine (stick)", serving: "1 tsp", exchanges: 1 },
      { name: "Buttery spread (light)", serving: "1 1/2 tsp", exchanges: 1 },
      { name: "Mayonnaise (light)", serving: "1 tbsp", exchanges: 1 },
      { name: "Mayonnaise (regular)", serving: "1 tsp", exchanges: 1 },
      { name: "Mayonnaise (olive oil)", serving: "1 tbsp", exchanges: 1.5 },
      { name: "Aioli (light)", serving: "1 tbsp", exchanges: 1.5 },
      { name: "Salad dressing (light vinaigrette)", serving: "2 tbsp", exchanges: 1 },
      { name: "Salad dressing (regular vinaigrette)", serving: "1 tbsp", exchanges: 1 },
      { name: "Italian dressing (light)", serving: "2 tbsp", exchanges: 1 },
      { name: "Ranch dressing (light)", serving: "2 tbsp", exchanges: 1 },
      { name: "Blue cheese dressing (light)", serving: "2 tbsp", exchanges: 1 },
      { name: "Thousand island (light)", serving: "2 tbsp", exchanges: 1 },
      { name: "Balsamic glaze / reduction", serving: "1 tbsp", exchanges: 1 },
      { name: "Tahini", serving: "1 tsp", exchanges: 1 },
      { name: "Tahini paste (sesame)", serving: "1 tsp", exchanges: 1 },
      { name: "Hummus", serving: "2 tbsp", exchanges: 1, tips: "Works as a fat and a little protein." },
      { name: "Baba ghanoush", serving: "2 tbsp", exchanges: 1 },
      { name: "Mutabbal / eggplant dip", serving: "2 tbsp", exchanges: 1 },
      { name: "Tzatziki (light)", serving: "3 tbsp", exchanges: 1 },
      { name: "Guacamole (no added oil)", serving: "2 tbsp", exchanges: 1 },
      { name: "Salsa (oil-based)", serving: "2 tbsp", exchanges: 0.5 },
      { name: "Pesto (light)", serving: "1 tbsp", exchanges: 1 },
      { name: "Tapenade (olive spread)", serving: "1 tbsp", exchanges: 1 },
      { name: "Peanut butter (no added oil)", serving: "2 tsp", exchanges: 1, tips: "Spread thin on apple slices — filling snack." },
      { name: "Peanut butter (creamy)", serving: "2 tsp", exchanges: 1 },
      { name: "Peanut butter (crunchy)", serving: "2 tsp", exchanges: 1 },
      { name: "Almond butter", serving: "2 tsp", exchanges: 1 },
      { name: "Cashew butter", serving: "2 tsp", exchanges: 1 },
      { name: "Hazelnut butter", serving: "2 tsp", exchanges: 1 },
      { name: "Walnut butter", serving: "2 tsp", exchanges: 1 },
      { name: "Sunflower seed butter", serving: "2 tsp", exchanges: 1 },
      { name: "Pumpkin seed butter", serving: "2 tsp", exchanges: 1 },
      { name: "Tahini butter / sesame butter", serving: "2 tsp", exchanges: 1 },
      { name: "Soy nut butter", serving: "2 tsp", exchanges: 1 },
      { name: "Coconut butter / manna", serving: "2 tsp", exchanges: 1.5 },
      { name: "Nutella-style spread (light)", serving: "2 tsp", exchanges: 1.5 },
      { name: "Shortening (vegetable)", serving: "1 tsp", exchanges: 1 },
      { name: "Lard (light portion)", serving: "1 tsp", exchanges: 1.5 },
      { name: "Suet (beef fat)", serving: "1 tsp", exchanges: 1.5 },
      { name: "Cooking spray (light oil)", serving: "3 second spray", exchanges: 0.5 },
      { name: "Whipped butter", serving: "1 1/2 tsp", exchanges: 1 },
      { name: "Avocado", serving: "1/8 whole fruit (2 tbsp)", exchanges: 1, tips: "Creamy swap for mayo in sandwiches." },
      { name: "Avocado slices (4 thin)", serving: "4 thin slices", exchanges: 0.5 },
      { name: "Olives (black / green)", serving: "8 large", exchanges: 1 },
      { name: "Black olives", serving: "10 large", exchanges: 1 },
      { name: "Green olives", serving: "10 large", exchanges: 1 },
      { name: "Kalamata olives", serving: "8 large", exchanges: 1 },
      { name: "Nicoise olives", serving: "12 small", exchanges: 1 },
      { name: "Almonds", serving: "6 whole nuts", exchanges: 1 },
      { name: "Slivered almonds", serving: "2 tbsp", exchanges: 1 },
      { name: "Almond slices", serving: "2 tbsp", exchanges: 1 },
      { name: "Walnuts", serving: "4 halves", exchanges: 1, tips: "Omega-3 plant source." },
      { name: "Peanuts (roasted)", serving: "10 nuts", exchanges: 1 },
      { name: "Peanuts (dry-roasted, unsalted)", serving: "10 nuts", exchanges: 1 },
      { name: "Pistachios", serving: "16 nuts", exchanges: 1, tips: "In-shell eating = slower, more mindful." },
      { name: "Cashews", serving: "6 nuts", exchanges: 1 },
      { name: "Macadamia nuts", serving: "4 whole", exchanges: 1.5 },
      { name: "Hazelnuts", serving: "8 whole", exchanges: 1 },
      { name: "Pecans", serving: "4 halves", exchanges: 1 },
      { name: "Brazil nuts", serving: "3 whole", exchanges: 1 },
      { name: "Pine nuts / pignoli", serving: "1 tbsp", exchanges: 1 },
      { name: "Pili nuts", serving: "6 whole", exchanges: 1 },
      { name: "Chestnuts (roasted, unsalted)", serving: "5 whole", exchanges: 1 },
      { name: "Water chestnuts", serving: "1/2 cup sliced", exchanges: 0.5 },
      { name: "Pumpkin / squash seeds", serving: "1 tbsp", exchanges: 1 },
      { name: "Pepitas / pumpkin seed kernels", serving: "1 tbsp", exchanges: 1 },
      { name: "Sunflower seeds", serving: "1 tbsp", exchanges: 1 },
      { name: "Sesame seeds", serving: "1 tbsp", exchanges: 1 },
      { name: "Flax seeds (whole)", serving: "1 tbsp", exchanges: 1 },
      { name: "Ground flaxseed / flax meal", serving: "1 tbsp", exchanges: 1 },
      { name: "Chia seeds", serving: "1 tbsp", exchanges: 1 },
      { name: "Hemp seeds / hemp hearts", serving: "1 tbsp", exchanges: 1 },
      { name: "Poppy seeds", serving: "1 tbsp", exchanges: 1 },
      { name: "Coconut (shredded, unsweetened)", serving: "2 tbsp", exchanges: 1 },
      { name: "Coconut (toasted flakes)", serving: "2 tbsp", exchanges: 1 },
      { name: "Coconut cream (light)", serving: "2 tbsp", exchanges: 1.5 },
      { name: "Coconut milk (light, canned)", serving: "3 tbsp", exchanges: 1.5 },
      { name: "Sour cream (light)", serving: "2 tbsp", exchanges: 1 },
      { name: "Sour cream (regular)", serving: "1 tbsp", exchanges: 1 },
      { name: "Soured milk / clabber", serving: "3 tbsp", exchanges: 0.5 },
      { name: "Crème fraîche (light)", serving: "1 tbsp", exchanges: 1 },
      { name: "Heavy cream / double cream", serving: "1 tbsp", exchanges: 2 },
      { name: "Whipping cream (light pour)", serving: "2 tbsp", exchanges: 1.5 },
      { name: "Half and half", serving: "2 tbsp", exchanges: 0.5 },
      { name: "Whipped cream (light)", serving: "1/4 cup", exchanges: 1 },
      { name: "Cream substitute (light)", serving: "3 tbsp", exchanges: 1 },
      { name: "Bacon bits (imitation)", serving: "1 tbsp", exchanges: 0.5 },
      { name: "Fried onions (crispy, small portion)", serving: "1 tbsp", exchanges: 1 },
      { name: "Roasted sesame seeds", serving: "1 tbsp", exchanges: 1 },
    ],
  },
];

export function getExchangeGroup(category: ExchangeCategory): ExchangeGroup {
  const g = FOOD_GROUPS_REFERENCE.find((x) => x.category === category);
  if (!g) throw new Error(`Unknown exchange category: ${category}`);
  return g;
}

export function findReferenceFood(
  category: ExchangeCategory,
  name: string,
): ReferenceFood | undefined {
  const g = getExchangeGroup(category);
  const q = name.toLowerCase();
  return (
    g.foods.find((f) => f.name.toLowerCase().includes(q)) ??
    g.foods.find((f) => q.includes(f.name.toLowerCase()))
  );
}
